"""
Domain Registry - Schemas + Alias Libraries.
Extracted from Notebooks 01-05
"""

# ── Domain 1: Sales / CRM ─────────────────────────────────────────────────────
SALES_SCHEMA = {
    "customer_id":   {"type": "string",   "required": True},
    "customer_name": {"type": "string",   "required": True},
    "email":         {"type": "string",   "required": False},
    "phone":         {"type": "string",   "required": False},
    "revenue":       {"type": "float",    "required": True},
    "deal_stage":    {"type": "string",   "required": True},
    "close_date":    {"type": "datetime", "required": True},
    "sales_rep":     {"type": "string",   "required": False},
    "region":        {"type": "string",   "required": False},
    "product":       {"type": "string",   "required": False},
    "quantity":      {"type": "int",      "required": False},
    "discount":      {"type": "float",    "required": False},
    "lead_source":   {"type": "string",   "required": False},
}


SALES_ALIASES = {
    "customer_id":   ["cust_id","customer_no","client_id","client_no","cid","account_id","acc_id","buyer_id","contact_id","user_id","customerid","custid","c_id"],
    "customer_name": ["cust_name","client_name","company","company_name","account_name","buyer_name","contact_name","name","full_name","org_name","organisation","organization","firm"],
    "email":         ["email_address","mail","e_mail","contact_email","cust_email","client_email","email_id","emailid","work_email"],
    "phone":         ["phone_no","phone_number","contact_no","mobile","mobile_no","cell","cell_no","telephone","tel","contact_phone","ph_no"],
    "revenue":       ["rev","rev_amt","revenue_amount","total_sales","sale_value","deal_value","amount","amt","total_amount","total_value","sales_amount","sales_amt","contract_value","deal_amount","total_revenue","value","order_value","mrr","arr","acv","tcv","ltv","monthly_recurring_revenue","annual_recurring_revenue","annual_contract_value"],
    "deal_stage":    ["stage","pipeline_stage","opportunity_stage","status","deal_status","sales_stage","crm_stage","phase","opp_stage","opportunity_status","lead_stage"],
    "close_date":    ["closed_date","closing_date","date_closed","close_dt","deal_date","sale_date","date_of_sale","transaction_date","order_date","date","closing_dt","won_date"],
    "sales_rep":     ["rep","rep_name","sales_person","salesperson","agent","agent_name","account_exec","ae","assigned_to","owner","sales_exec","executive","handled_by"],
    "region":        ["territory","geo","geography","area","zone","location","market","country","state","city","branch"],
    "product":       ["product_name","item","item_name","service","service_name","sku","product_code","offering","plan","package"],
    "quantity":      ["qty","units","no_of_units","count","volume","num_units","unit_count","seats","licenses"],
    "discount":      ["disc","discount_pct","discount_percent","disc_pct","rebate","markdown","price_reduction","offer_pct"],
    "lead_source":   ["source","lead_origin","acquisition_channel","channel","marketing_source","referral","campaign","utm_source","how_found","origin"],
}

# ── Domain 2: E-commerce / Orders ────────────────────────────────────────────
ECOMMERCE_SCHEMA = {
    "order_id":         {"type": "string",   "required": True},
    "customer_id":      {"type": "string",   "required": True},
    "customer_name":    {"type": "string",   "required": False},
    "email":            {"type": "string",   "required": False},
    "product_id":       {"type": "string",   "required": True},
    "product_name":     {"type": "string",   "required": False},
    "category":         {"type": "string",   "required": False},
    "unit_price":       {"type": "float",    "required": True},
    "quantity":         {"type": "int",      "required": True},
    "total_price":      {"type": "float",    "required": True},
    "discount":         {"type": "float",    "required": False},
    "order_status":     {"type": "string",   "required": True, "enum": ["pending","processing","shipped","delivered","cancelled","returned"]},
    "payment_method":   {"type": "string",   "required": False},
    "order_date":       {"type": "datetime", "required": True},
    "delivery_date":    {"type": "datetime", "required": False},
    "shipping_address": {"type": "string",   "required": False},
    "region":           {"type": "string",   "required": False},
}
 
ECOMMERCE_ALIASES = {
    "order_id":         ["order_no","order_number","ord_id","ordid","transaction_id","txn_id","invoice_no","invoice_id","receipt_no","ref_no","reference_no","booking_id","purchase_id"],
    "customer_id":      ["cust_id","customer_no","client_id","buyer_id","user_id","account_id","shopper_id","member_id","cid","custid"],
    "customer_name":    ["cust_name","buyer_name","client_name","full_name","name","billing_name","ship_to_name","recipient"],
    "email":            ["email_address","mail","e_mail","customer_email","buyer_email","contact_email","email_id","emailid"],
    "product_id":       ["prod_id","product_no","item_id","item_no","item_code","sku","sku_id","sku_code","variant_id","variant_code","asin","product_code","article_no","barcode","ean","upc","listing_id"],
    "product_name":     ["item_name","product_title","item_title","product_description","item_description","title","name","good_name","article_name"],
    "category":         ["product_category","item_category","cat","dept","department","product_type","item_type","classification","segment"],
    "unit_price":       ["price","price_per_unit","item_price","selling_price","sale_price","mrp","list_price","base_price","unit_cost","cost_price","rate"],
    "quantity":         ["qty","units","no_of_units","count","volume","num_units","unit_count","pieces","pcs","items_ordered"],
    "total_price":      ["total","total_amount","order_total","order_value","grand_total","net_amount","net_total","invoice_amount","bill_amount","payable_amount","amount_due","subtotal"],
    "discount":         ["disc","discount_pct","discount_percent","disc_pct","offer_pct","coupon_discount","promo_discount","markdown","rebate"],
    "order_status":     ["status","order_state","fulfillment_status","shipment_status","delivery_status","tracking_status","state","dispatch_status"],
    "payment_method":   ["payment","payment_type","pay_mode","payment_mode","mode_of_payment","payment_channel","pay_type","checkout_method"],
    "order_date":       ["date","order_time","purchase_date","transaction_date","created_at","created_date","placed_on","booking_date","date_ordered"],
    "delivery_date":    ["delivered_date","delivery_time","date_delivered","shipped_date","dispatch_date","fulfillment_date","estimated_delivery","eta","expected_delivery"],
    "shipping_address": ["address","delivery_address","ship_to","ship_to_address","billing_address","postal_address","drop_address"],
    "region":           ["country","state","city","location","area","zone","territory","market","geo","branch"],
}
 

# ── Domain 3: Finance / Invoicing ─────────────────────────────────────────────
FINANCE_SCHEMA = {
    "invoice_id":      {"type": "string",   "required": True},
    "vendor_id":       {"type": "string",   "required": True},
    "vendor_name":     {"type": "string",   "required": False},
    "customer_id":     {"type": "string",   "required": True},
    "customer_name":   {"type": "string",   "required": False},
    "invoice_date":    {"type": "datetime", "required": True},
    "due_date":        {"type": "datetime", "required": True},
    "invoice_amount":  {"type": "float",    "required": True},
    "tax_rate":        {"type": "float",    "required": False},
    "tax_amount":      {"type": "float",    "required": True},
    "discount":        {"type": "float",    "required": False},
    "total_amount":    {"type": "float",    "required": True},
    "currency":        {"type": "string",   "required": True},
    "payment_status":  {"type": "string",   "required": True, "enum": ["paid","unpaid","overdue","partial","cancelled"]},
    "payment_date":    {"type": "datetime", "required": False},
    "payment_method":  {"type": "string",   "required": False},
    "notes":           {"type": "string",   "required": False},
}
 
FINANCE_ALIASES = {
    "invoice_id":      ["inv_id","inv_no","invoice_no","invoice_number","bill_no","bill_id","bill_number","receipt_no","voucher_no","txn_id","document_no","doc_no","ref_no","belnr"],
    "vendor_id":       ["vendor_no","supplier_id","supplier_no","supplier_number","lifnr","party_id","seller_id","creditor_id","payee_id"],
    "vendor_name":     ["supplier_name","seller_name","party_name","creditor_name","payee_name","vendor","supplier","company_name","firm_name"],
    "customer_id":     ["cust_id","client_id","buyer_id","debtor_id","account_id","kunnr","customer_no","bill_to_id"],
    "customer_name":   ["cust_name","client_name","buyer_name","debtor_name","bill_to","bill_to_name","account_name"],
    "invoice_date":    ["inv_date","bill_date","issue_date","date_of_invoice","raised_on","created_date","bldat","invoice_raised_date","doc_date"],
    "due_date":        ["due_on","payment_due","payment_due_date","pay_by","expiry_date","maturity_date","zfbdt","net_due_date","deadline"],
    "invoice_amount":  ["inv_amt","bill_amt","base_amount","net_amount","amount","amt","subtotal","taxable_amount","invoice_value","bill_value","dmbtr"],
    "tax_rate":        ["tax_pct","tax_percent","gst_rate","vat_rate","tax_%","rate_of_tax","mwskz"],
    "tax_amount":      ["tax","gst","vat","gst_amount","vat_amount","tax_value","tax_charged","hwste","cgst","sgst","igst"],
    "discount":        ["disc","discount_amt","discount_amount","rebate","trade_discount","cash_discount","skfbt"],
    "total_amount":    ["total","grand_total","net_payable","amount_due","payable_amount","final_amount","total_bill","total_invoice","invoice_total","wrbtr"],
    "currency":        ["currency_code","curr","ccy","currency_type","waers","transaction_currency","billing_currency"],
    "payment_status":  ["status","pay_status","invoice_status","payment_state","settlement_status","clearance_status","paid_status"],
    "payment_date":    ["paid_on","date_paid","payment_received","cleared_on","settlement_date","value_date","zbd1t"],
    "payment_method":  ["pay_mode","payment_type","payment_channel","mode_of_payment","pay_type","zlsch"],
    "notes":           ["remarks","comments","memo","description","narration","note","details","sgtxt"],
}
 
# ── Domain 4: Delivery / Logistics ───────────────────────────────────────────
LOGISTICS_SCHEMA = {
    "tracking_id":       {"type": "string",   "required": True},
    "order_id":          {"type": "string",   "required": True},
    "carrier":           {"type": "string",   "required": True},
    "carrier_service":   {"type": "string",   "required": False},
    "sender_id":         {"type": "string",   "required": False},
    "sender_name":       {"type": "string",   "required": False},
    "receiver_id":       {"type": "string",   "required": True},
    "receiver_name":     {"type": "string",   "required": False},
    "origin":            {"type": "string",   "required": True},
    "destination":       {"type": "string",   "required": True},
    "origin_lat":        {"type": "float",    "required": False},
    "origin_lng":        {"type": "float",    "required": False},
    "dest_lat":          {"type": "float",    "required": False},
    "dest_lng":          {"type": "float",    "required": False},
    "distance":          {"type": "float",    "required": False},
    "distance_unit":     {"type": "string",   "required": False},
    "pickup_date":       {"type": "datetime", "required": True},
    "expected_delivery": {"type": "datetime", "required": True},
    "actual_delivery":   {"type": "datetime", "required": False},
    "delivery_status":   {"type": "string",   "required": True, "enum": ["pending","picked_up","in_transit","out_for_delivery","delivered","failed","returned"]},
    "weight_kg":         {"type": "float",    "required": False},
    "cod_amount":        {"type": "float",    "required": False},
}
 
LOGISTICS_ALIASES = {
    "tracking_id":       ["tracking_no","tracking_number","track_id","shipment_id","consignment_no","consignment_id","cn_no","cn_number","awb_no","awb_number","awb","waybill_no","waybill","dhl_ref","master_tracking_no","wbn","delhivery_tracking","amzl_tracking","lrn","lr_no"],
    "order_id":          ["order_no","order_number","ref_order_id","purchase_order","po_no","po_number","sale_order_id","so_no"],
    "carrier":           ["courier","courier_name","logistics_partner","shipping_partner","carrier_name","shipper","delivery_partner","transport_company","3pl","logistics_provider"],
    "carrier_service":   ["service_type","shipping_mode","delivery_mode","service_level","shipment_type","courier_service","transit_type"],
    "sender_id":         ["shipper_id","from_id","seller_id","dispatch_id","origin_id"],
    "sender_name":       ["shipper_name","from_name","seller_name","dispatch_name","consignor","consignor_name"],
    "receiver_id":       ["recipient_id","to_id","customer_id","buyer_id","consignee_id","delivery_id"],
    "receiver_name":     ["recipient_name","to_name","customer_name","buyer_name","consignee","consignee_name","deliver_to"],
    "origin":            ["from_city","from_location","pickup_city","pickup_location","source_city","source","dispatch_city","origin_city","from_hub","origin_hub","from_warehouse"],
    "destination":       ["to_city","to_location","delivery_city","delivery_location","dest_city","dest","drop_city","destination_city","to_hub","destination_hub","delivery_address_city"],
    "origin_lat":        ["from_lat","pickup_lat","source_lat","origin_latitude"],
    "origin_lng":        ["from_lng","pickup_lng","source_lng","origin_longitude"],
    "dest_lat":          ["to_lat","delivery_lat","destination_lat","dest_latitude"],
    "dest_lng":          ["to_lng","delivery_lng","destination_lng","dest_longitude"],
    "distance":          ["route_distance","total_distance","km","miles","dist","travel_distance","trip_distance"],
    "distance_unit":     ["unit","dist_unit","distance_measure","measurement_unit"],
    "pickup_date":       ["pickup_time","dispatch_date","dispatch_time","collected_on","picked_on","collection_date","shipped_date","shipped_on"],
    "expected_delivery": ["eta","estimated_delivery","promised_date","delivery_eta","expected_date","sla_date","commitment_date","due_delivery"],
    "actual_delivery":   ["delivered_date","delivery_date","delivered_on","date_delivered","actual_date","pod_date","completion_date"],
    "delivery_status":   ["status","shipment_status","tracking_status","order_status","delivery_state","current_status","shipment_state","courier_status","fulfillment_status","last_status"],
    "weight_kg":         ["weight","wt","wt_kg","shipment_weight","parcel_weight","gross_weight","actual_weight","chargeable_weight"],
    "cod_amount":        ["cod","cash_on_delivery","cod_value","collection_amount","cod_amt","cod_charge","cash_to_collect"],
}
 
# ── Domain 5: HR / Payroll ────────────────────────────────────────────────────
HR_SCHEMA = {
    "employee_id":       {"type": "string",   "required": True},
    "full_name":         {"type": "string",   "required": True},
    "date_of_birth":     {"type": "datetime", "required": True},
    "date_of_joining":   {"type": "datetime", "required": True},
    "department":        {"type": "string",   "required": True},
    "designation":       {"type": "string",   "required": True},
    "employment_status": {"type": "string",   "required": True, "enum": ["active","inactive","on_leave","terminated","probation"]},
    "basic_salary":      {"type": "float",    "required": True},
    "hra":               {"type": "float",    "required": False},
    "allowances":        {"type": "float",    "required": False},
    "gross_salary":      {"type": "float",    "required": True},
    "total_deductions":  {"type": "float",    "required": False},
    "tax_deducted":      {"type": "float",    "required": False},
    "net_salary":        {"type": "float",    "required": True},
    "pay_date":          {"type": "datetime", "required": True},
    "pay_period_start":  {"type": "datetime", "required": True},
    "pay_period_end":    {"type": "datetime", "required": True},
    "bank_account":      {"type": "string",   "required": False, "pii": True},
    "pan_no":            {"type": "string",   "required": False, "pii": True},
    "aadhar_no":         {"type": "string",   "required": False, "pii": True},
    "pf_number":         {"type": "string",   "required": False},
    "manager_id":        {"type": "string",   "required": False},
    "location":          {"type": "string",   "required": False},
}
 
HR_ALIASES = {
    "employee_id":       ["emp_id","emp_code","employee_code","staff_id","staff_no","worker_id","personnel_no","person_id","associate_id","pernr","worker_number","team_member_id"],
    "full_name":         ["emp_name","employee_name","name","staff_name","worker_name","associate_name","personnel_name","first_last_name","preferred_name"],
    "date_of_birth":     ["dob","birth_date","birthdate","date_birth","born_on","birth_dt"],
    "date_of_joining":   ["doj","joining_date","hire_date","start_date","employment_start","date_hired","onboard_date","entry_date","contract_start"],
    "department":        ["dept","dept_name","division","business_unit","bu","cost_center","team","function","org_unit","orgeh"],
    "designation":       ["job_title","title","role","position","job_role","grade","level","cadre","rank","post"],
    "employment_status": ["status","emp_status","staff_status","worker_status","employment_type","contract_status","active_status"],
    "basic_salary":      ["basic","basic_pay","base_salary","base_pay","basic_wage","base_wage","fixed_pay","basic_ctc"],
    "hra":               ["house_rent_allowance","rent_allowance","hra_amount","housing_allowance","accommodation_allowance"],
    "allowances":        ["other_allowances","special_allowance","misc_allowance","conveyance","transport_allowance","medical_allowance","lta","food_allowance","variable_pay","bonus"],
    "gross_salary":      ["gross","gross_pay","gross_ctc","ctc","total_earnings","total_pay","gross_wage","annual_salary","total_compensation","total_salary"],
    "total_deductions":  ["deductions","total_deduction","deduction_amount","pf_deduction","esi_deduction","statutory_deductions","total_cuts","recovery"],
    "tax_deducted":      ["tds","tds_amount","income_tax","tax_withheld","withholding_tax","fica","paye_tax","tax_deduction","it_deduction"],
    "net_salary":        ["net","net_pay","take_home","take_home_pay","in_hand","in_hand_salary","net_wage","net_earnings","salary_credited","amount_paid"],
    "pay_date":          ["salary_date","payment_date","credit_date","disbursement_date","payout_date","salary_credit_date"],
    "pay_period_start":  ["period_start","payroll_start","month_start","salary_from","pay_from","attendance_from"],
    "pay_period_end":    ["period_end","payroll_end","month_end","salary_to","pay_to","attendance_to"],
    "bank_account":      ["account_no","account_number","bank_acc","bank_acc_no","salary_account","acc_no","bank_number"],
    "pan_no":            ["pan","pan_card","pan_number","tax_id","ssn","social_security","ni_number","national_insurance","tax_identification","tin"],
    "aadhar_no":         ["aadhar","aadhaar","uid","aadhar_card","uidai_no","unique_id"],
    "pf_number":         ["pf_no","pf_account","provident_fund_no","epf_no","epf_account","retirement_account","k401","pension_account"],
    "manager_id":        ["reporting_manager","manager","supervisor_id","reports_to","line_manager_id","team_lead_id"],
    "location":          ["office","office_location","work_location","branch","work_city","work_site","base_location","posting"],
}
 
# ── Domain Registry ───────────────────────────────────────────────────────────
DOMAINS = {
    "sales":      {"schema": SALES_SCHEMA,     "aliases": SALES_ALIASES,     "label": "Sales / CRM"},
    "ecommerce":  {"schema": ECOMMERCE_SCHEMA, "aliases": ECOMMERCE_ALIASES, "label": "E-commerce / Orders"},
    "finance":    {"schema": FINANCE_SCHEMA,   "aliases": FINANCE_ALIASES,   "label": "Finance / Invoicing"},
    "logistics":  {"schema": LOGISTICS_SCHEMA, "aliases": LOGISTICS_ALIASES, "label": "Delivery / Logistics"},
    "hr":         {"schema": HR_SCHEMA,        "aliases": HR_ALIASES,        "label": "HR / Payroll"},
}